@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "What is dthe capita of France?",
  "content": "I need to know the capital city of France for my geography project."
}

###
# @name recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name edit_questions
PUT {{baseUrl}}/questions/86c5fd1f-a91f-4cac-824b-5c7567d394b2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "New title",
  "content": "New content"
}

###
# @name delete_questions
DELETE {{baseUrl}}/questions/86c5fd1f-a91f-4cac-824b-5c7567d394b2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name answer_questions
POST {{baseUrl}}/questions/7d98ca4f-279e-4644-aaa0-f9858d64a440/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "The capital of France is Paris."
}