version: ''

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_clean_forum
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres